spring:
  datasource:
    master:
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
      jdbcUrl: jdbc:mysql://192.168.1.230:3306/rb_warehouse_1001?useUnicode=true&nullCatalogMeansCurrent=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: root
server:
  port: 9000

#page分页配置
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql




