#指定注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.231:8660/eureka/
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
spring:
  datasource:
    the-host:
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
      jdbcUrl: jdbc:mysql://192.168.1.230:3306/rb_warehouse_1001?useUnicode=true&nullCatalogMeansCurrent=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: root
  application:
    name: web-service
  servlet:
    multipart:
      max-file-size:  100MB
      max-request-size: 100MB
  redis:
    database: 0
    #连接的地址
    host: 192.168.1.230
    #超时时间：单位ms
    timeout: 5000
    #端口号
    port: 6379
    ##最大连接数：能够同时建立的“最大链接个数”
    pool:
      maxActive: 2000
      #最大空闲数：空闲链接数大于maxIdle时，将进行回收
      maxIdle: 200
      #最小空闲数：低于minIdle时，将创建新的链接
      minIdle: 200
      #最大等待时间：单位ms
      maxWait: 1000
#自定义负载均衡策略
#product-service:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
#请求处理的超时时间
ribbon:
  ReadTimeout: 4000
  #请求连接的超时时间
  ConnectTimeout: 3000
#hystrix 配置
hystrix:
  command:
    default:
      execution:
        timeout:
          #如果enabled设置为false，则请求超时交给ribbon控制
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 5000
server:
  port: 9000
#page分页配置
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

sso.server: http://192.168.1.231:9001
sso.login.path: /api/v1/sso/login #登陆url
sso.logout.path: /api/v1/sso/logout #登出url
sso.logout.workerId: 0  #雪花算法机器标识
sso.logout.datacenterId: 0 #雪花算法机器标识

#生成订单一些前缀
transfer.db: DB_ #调拨key
fba: FBA_ # fba key
token: TOKEN_IDE # 幂等token  key

#静态常量 一些基本的配置文件
static:
  variable:
    ssoToken: sso-token
    maxWait: 5000
    timeout: 20000
    admin: admin
    db: DB
    dbEId: DBEID
    fba: FBA
    fbaEId: FBAEID
    ideToken: ide-token
    saveFilePath: /usr/local/file/path/
    fileW: D://template/fba导入模板.xlsx
    fileL: /usr/local/file/template/





